### ISSUE TITLE
what is key and value means?

### ISSUE THREAD

**Issue by yml-blog** [devOpifex/mapper#1]
"key", "value" in the input. Thanks so much

**Comment by JohnCoene** [comment]
This is just the standard way of referring to these within a [map](https://en.wikipedia.org/wiki/Map_(higher-order_function)), e.g.: [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).

Note there is also [fastmap](https://github.com/r-lib/fastmap)
